"""`duck-test` — a thin front-end over pytest for the duckdb test lane.

Subcommands:
  configure   Write the base pytest config into a repo so bare `pytest` just works.

The plugin (auto-registered via the pytest11 entry point) supplies every default it can at
runtime — working dir, test root, `.test` collection, `--build`. The few settings a plugin
*cannot* inject (addopts/xdist, testpaths, --import-mode, python_files) live in the config
this command writes; after `duck-test configure`, plain `pytest` works with no other setup.
"""

import argparse
import difflib
import os
import sys

# The canonical config `configure` writes. Kept in sync with README.md's documented stub.
_PYTEST_INI = """\
[pytest]
# Generated by `duck-test configure` — re-run it to refresh. Safe to edit by hand
# (configure won't overwrite a modified copy; it stops and shows a diff instead).
#
# -n auto + loadgroup need the [xdist] extra installed; drop them for single-process.
addopts = -n auto --dist=loadgroup --import-mode=importlib
# Keep pytest out of scripts/, tools/, third_party/, and nested checkouts.
testpaths = test
# The driver collector owns .test discovery; disable pytest's native test_*.py pickup
# (many duckdb repos ship non-pytest scripts named test_*.py that sys.exit at import).
python_files =
"""

# name -> content. A dict so more base files can be added without reworking the flow.
_BASE_FILES = {"pytest.ini": _PYTEST_INI}


def _configure(args):
    target_dir = os.path.abspath(args.dir)
    if not os.path.isdir(target_dir):
        sys.stderr.write("✗ not a directory: %s\n" % target_dir)
        return 2
    rc = 0
    for name, want in _BASE_FILES.items():
        path = os.path.join(target_dir, name)
        if os.path.exists(path):
            with open(path, "r") as f:
                have = f.read()
            if have == want:
                print("✓ %s already up to date" % path)
                continue
            # Exists and differs: never clobber. Show what's different and fail.
            sys.stderr.write("✗ %s exists and differs from the duck-test template — not overwriting.\n" % path)
            diff = difflib.unified_diff(
                have.splitlines(True), want.splitlines(True), fromfile="%s (on disk)" % name, tofile="%s (template)" % name
            )
            sys.stderr.writelines(diff)
            sys.stderr.write("\n  Reconcile (or remove the file) and re-run `duck-test configure`.\n")
            rc = 1
            continue
        with open(path, "w") as f:
            f.write(want)
        print("✓ wrote %s" % path)
    return rc


def main(argv=None):
    parser = argparse.ArgumentParser(prog="duck-test", description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_cfg = sub.add_parser("configure", help="write the base pytest config so bare `pytest` works")
    p_cfg.add_argument("dir", nargs="?", default=".", help="target repo dir (default: cwd)")
    p_cfg.set_defaults(func=_configure)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
