"""`ducktest` — a thin front-end over pytest for the duckdb test lane.

Subcommands:
  configure           Write the base pytest config into a repo so bare `pytest` just works.
  provision-service   Start declared service(s) out-of-session and leave them running.
  teardown-service    Stop declared service(s) started out-of-session.

The plugin (auto-registered via the pytest11 entry point) supplies every default it can at
runtime — working dir, test root, `.test` collection, `--build`. The few settings a plugin
*cannot* inject (addopts/xdist, testpaths, --import-mode, python_files) live in the config
this command writes; after `ducktest configure`, plain `pytest` works with no other setup.

`provision-service` / `teardown-service` are THIN SHIMS over pytest: they shell
`python -m pytest --provision-service <keys>` in THIS interpreter's env (so pytest + the plugin +
the test deps are the same env the shim runs in — the install model). The real work is the pytest
invocation-mode; see docs/SERVICES.md.
"""

import argparse
import difflib
import os
import subprocess
import sys

# The canonical config `configure` writes. Kept in sync with README.md's documented stub.
_PYTEST_INI = """\
[pytest]
# Generated by `ducktest configure` — re-run it to refresh. Safe to edit by hand
# (configure won't overwrite a modified copy; it stops and shows a diff instead).
#
# -n auto + loadgroup need the [xdist] extra installed; drop them for single-process.
addopts = -n auto --dist=loadgroup --import-mode=importlib
# Keep pytest out of scripts/, tools/, third_party/, and nested checkouts.
testpaths = test
# The driver collector owns .test discovery; disable pytest's native test_*.py pickup
# (many duckdb repos ship non-pytest scripts named test_*.py that sys.exit at import).
python_files =
"""

# name -> content. A dict so more base files can be added without reworking the flow.
_BASE_FILES = {"pytest.ini": _PYTEST_INI}


def _configure(args):
    target_dir = os.path.abspath(args.dir)
    if not os.path.isdir(target_dir):
        sys.stderr.write("✗ not a directory: %s\n" % target_dir)
        return 2
    rc = 0
    for name, want in _BASE_FILES.items():
        path = os.path.join(target_dir, name)
        if os.path.exists(path):
            with open(path, "r") as f:
                have = f.read()
            if have == want:
                print("✓ %s already up to date" % path)
                continue
            # Exists and differs: never clobber. Show what's different and fail.
            sys.stderr.write("✗ %s exists and differs from the ducktest template — not overwriting.\n" % path)
            diff = difflib.unified_diff(
                have.splitlines(True),
                want.splitlines(True),
                fromfile="%s (on disk)" % name,
                tofile="%s (template)" % name,
            )
            sys.stderr.writelines(diff)
            sys.stderr.write("\n  Reconcile (or remove the file) and re-run `ducktest configure`.\n")
            rc = 1
            continue
        with open(path, "w") as f:
            f.write(want)
        print("✓ wrote %s" % path)
    return rc


def _service_cmd(args, flag):
    """Shim: shell `python -m pytest <flag>[=keys] <passthrough>` in this interpreter's env."""
    opt = flag if not args.keys else f"{flag}={args.keys}"
    cmd = [sys.executable, "-m", "pytest", opt, *args.pytest_args]
    return subprocess.call(cmd)


def main(argv=None):
    parser = argparse.ArgumentParser(prog="ducktest", description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_cfg = sub.add_parser("configure", help="write the base pytest config so bare `pytest` works")
    p_cfg.add_argument("dir", nargs="?", default=".", help="target repo dir (default: cwd)")
    p_cfg.set_defaults(func=_configure)

    # KNOWN LIMITATION (found in code review, 2026-07-14, not fixed): argparse can't disambiguate a
    # dash-leading pytest_args token from the optional `keys` positional when `keys` is omitted --
    # `ducktest teardown-service -p no:cacheprovider` errors "unrecognized arguments" instead of
    # targeting all services + forwarding -p. A `--` separator does NOT help either: argparse still
    # greedily binds the first REMAINDER-adjacent token to `keys` (`teardown-service -- -p no:x` parses
    # `-p` into `keys`, silently mistargeting the service filter instead of erroring). Workaround: pass
    # `keys` explicitly (`teardown-service '*' -p no:cacheprovider`) whenever forwarding a pytest flag.
    for name, flag, helptext in (
        ("provision-service", "--provision-service", "start declared service(s) and leave them running"),
        ("teardown-service", "--teardown-service", "stop declared service(s)"),
    ):
        p = sub.add_parser(name, help=helptext)
        p.add_argument("keys", nargs="?", default=None, help="comma-list of service keys (default: all)")
        p.add_argument(
            "pytest_args",
            nargs=argparse.REMAINDER,
            help="extra args forwarded to pytest (pass `keys` explicitly, e.g. '*', when using this -- "
            "a dash-leading arg can't be forwarded if `keys` is omitted, see the comment above)",
        )
        p.set_defaults(func=lambda a, _flag=flag: _service_cmd(a, _flag))

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
