"""`ducktest` — a thin front-end over pytest for the duckdb test lane.

Subcommands:
  configure           Write the base pytest config (+ a starter pyproject.toml) so `pytest` /
                      `uv run pytest` just work.
  provision-service   Start declared service(s) out-of-session and leave them running.
  teardown-service    Stop declared service(s) started out-of-session.
  publish-images      Publish the resource images (mirror or build) into the ghcr namespace.
  pull-images         Pre-pull the resources' served images (warm the cache / fail fast).

The plugin (auto-registered via the pytest11 entry point) supplies every default it can at
runtime — working dir, test root, `.test` collection, `--build`. The few settings a plugin
*cannot* inject (addopts/xdist, testpaths, --import-mode, python_files) live in the pytest.ini
this command writes; after `ducktest configure`, plain `pytest` works with no other setup. It
also drops a starter `pyproject.toml` (the test venv, for `uv run pytest`) beside it — written
once, then yours to edit; unlike pytest.ini, configure won't touch it again.

`provision-service` / `teardown-service` are THIN SHIMS over pytest: they shell
`python -m pytest --provision-service <keys>` in THIS interpreter's env (so pytest + the plugin +
the test deps are the same env the shim runs in — the install model). The real work is the pytest
invocation-mode; see docs/SERVICES.md.
"""

import argparse
import difflib
import os
import subprocess
import sys

# The canonical config `configure` writes. Kept in sync with README.md's documented stub.
_PYTEST_INI = """\
[pytest]
# Generated by `ducktest configure` — re-run it to refresh. Safe to edit by hand
# (configure won't overwrite a modified copy; it stops and shows a diff instead).
#
# -n auto + loadgroup need the [xdist] extra installed; drop them for single-process.
addopts = -n auto --dist=loadgroup --import-mode=importlib
# Keep pytest out of scripts/, tools/, third_party/, and nested checkouts.
testpaths = test
# The driver collector owns .test discovery; disable pytest's native test_*.py pickup
# (many duckdb repos ship non-pytest scripts named test_*.py that sys.exit at import).
python_files =
"""

# A starter `pyproject.toml`, written ONCE (see _SCAFFOLD_FILES): it declares the test *environment* so
# `uv run pytest` resolves everything pytest imports from one venv, and lives beside pytest.ini (which
# holds the pytest *config*). Unlike pytest.ini this is yours to grow — configure never rewrites it.
_PYPROJECT = """\
# pyproject.toml — a starter written ONCE by `ducktest configure`; after this it's YOURS (configure will
# never overwrite it). It declares this extension's TEST environment so `uv run pytest`, run from this
# dir, resolves everything pytest imports from a single venv. The pytest *config* lives next door in
# pytest.ini (also written by configure); deps live here.
#
# This repo is an EXTENSION, not a Python package, so `[tool.uv] package = false` stops uv from trying to
# build/install it — you still get `uv run pytest`. Your own test-support Python (generators, provisioners)
# imports via the driver's `duckdb_pythonpath`, not from here (see the driver README, "Python layout").

[project]
name = "CHANGEME-tests"           # any name; this project is never published
version = "0"
requires-python = ">=3.9"

[dependency-groups]
# Everything pytest imports, in ONE place — uv installs this `dev` group by default under `uv run`.
dev = [
    "duckdb-pytest-driver[xdist]",   # the driver; its [xdist] extra brings pytest + pytest-xdist
    # your extension's own test deps, e.g.:
    # "databricks-sdk",
    # "pyspark==4.0.1",
]

[tool.uv]
package = false

# The driver isn't published yet — resolve it from your local checkout (adjust if it isn't a sibling):
[tool.uv.sources]
duckdb-pytest-driver = { path = "../driver", editable = true }
"""

# ducktest OWNS these: it keeps them byte-exact and refuses to clobber a hand-edit (stops with a diff).
_OWNED_FILES = {"pytest.ini": _PYTEST_INI}
# ducktest SCAFFOLDS these: written only when absent, then left alone forever — yours to fill in. Kept
# separate from owned files precisely because you WILL edit them (real deps), so a diff must not block.
_SCAFFOLD_FILES = {"pyproject.toml": _PYPROJECT}


def _configure(args):
    target_dir = os.path.abspath(args.dir)
    if not os.path.isdir(target_dir):
        sys.stderr.write("✗ not a directory: %s\n" % target_dir)
        return 2
    rc = 0
    # Owned files: byte-exact or bust. A hand-edited copy stops configure with a diff (never clobbered).
    for name, want in _OWNED_FILES.items():
        path = os.path.join(target_dir, name)
        if os.path.exists(path):
            with open(path, "r") as f:
                have = f.read()
            if have == want:
                print("✓ %s already up to date" % path)
                continue
            # Exists and differs: never clobber. Show what's different and fail.
            sys.stderr.write("✗ %s exists and differs from the ducktest template — not overwriting.\n" % path)
            diff = difflib.unified_diff(
                have.splitlines(True),
                want.splitlines(True),
                fromfile="%s (on disk)" % name,
                tofile="%s (template)" % name,
            )
            sys.stderr.writelines(diff)
            sys.stderr.write("\n  Reconcile (or remove the file) and re-run `ducktest configure`.\n")
            rc = 1
            continue
        with open(path, "w") as f:
            f.write(want)
        print("✓ wrote %s" % path)
    # Scaffold files: a starting point you then own. Written only if absent — an existing one is left
    # untouched (your real deps are safe), reported, and never a failure.
    for name, want in _SCAFFOLD_FILES.items():
        path = os.path.join(target_dir, name)
        if os.path.exists(path):
            print("✓ %s exists — leaving it as-is (yours to edit)" % path)
            continue
        with open(path, "w") as f:
            f.write(want)
        print("✓ wrote %s (starter — add your test deps, then `uv run pytest`)" % path)
    return rc


def _service_cmd(args, flag):
    """Shim: shell `python -m pytest <flag>[=keys] <passthrough>` in this interpreter's env."""
    opt = flag if not args.keys else f"{flag}={args.keys}"
    cmd = [sys.executable, "-m", "pytest", opt, *args.pytest_args]
    return subprocess.call(cmd)


def _publish_images(args):
    """Publish the `resources.*` images into the ghcr namespace using ONLY core docker (no buildx).

    Two phases, both gated by `--push` (default = print the plan, run nothing):
      - default phase: publish this machine's per-arch slices as `…:<pin>-<arch>` tags. A `mirror` image
        copies every platform from one machine (`docker pull --platform` fetches any arch — we never RUN
        it, so no QEMU); a `build` image publishes only the host arch (native `docker build`), so run it
        once on an amd box and once on an arm box.
      - `--finalize`: stitch the per-arch tags into the multi-arch `…:<pin>` manifest (`docker manifest`).

    `docker login ghcr.io -u <user>` (token with `write:packages`) first. The pull side is automatic — a
    resource `docker run`s the ghcr ref once `DUCKTEST_IMAGE_SOURCE=ghcr`.
    """
    # Import the resource modules so their register_image() calls populate the registry (single source).
    from .resources import azurite, minio  # noqa: F401
    from .resources._images import IMAGE_NS, arch_of, ghcr_ref, host_arch, registry

    ns = (args.namespace or IMAGE_NS).rstrip("/")
    imgs = registry()
    if not imgs:
        sys.stderr.write("✗ no resource images registered\n")
        return 1

    def run(cmd, ignore=False):
        print("    $ " + " ".join(cmd))
        if not args.push:
            return 0
        proc = subprocess.run(cmd)
        return 0 if ignore else proc.returncode

    rc = 0
    if args.finalize:
        print("finalize -> multi-arch manifests in %s   (%s)" % (ns, "PUSH" if args.push else "dry run"))
        for name, e in imgs:
            target = ghcr_ref(name, e["pin"], ns=ns)
            archtags = ["%s-%s" % (target, arch_of(p)) for p in e["platforms"]]
            print("  %s  <-  %s" % (target, ", ".join(archtags)))
            run(["docker", "manifest", "rm", target], ignore=True)  # clear any stale local list
            if run(["docker", "manifest", "create", target, *archtags]) or run(["docker", "manifest", "push", target]):
                sys.stderr.write("✗ finalize failed for %s (are all per-arch slices pushed?)\n" % name)
                rc = 1
    else:
        arch = host_arch()
        print("publish per-arch slices to %s   (host arch %s; %s)" % (ns, arch, "PUSH" if args.push else "dry run"))
        for name, e in imgs:
            target = ghcr_ref(name, e["pin"], ns=ns)
            if e["kind"] == "mirror":
                for p in e["platforms"]:  # one machine covers every arch: pull doesn't execute the image
                    at = "%s-%s" % (target, arch_of(p))
                    print("  mirror %s [%s] -> %s" % (e["source"], p, at))
                    if (run(["docker", "pull", "--platform", p, e["source"]])
                            or run(["docker", "tag", e["source"], at])
                            or run(["docker", "push", at])):
                        sys.stderr.write("✗ mirror failed for %s [%s] (is `docker login ghcr.io` done?)\n" % (name, p))
                        rc = 1
            else:  # build: native host arch only (no QEMU) — run on each arch's machine
                p = "linux/%s" % arch
                if p not in e["platforms"]:
                    print("  build %s: host arch %s not in %s — nothing to do on this machine" % (name, p, e["platforms"]))
                    continue
                at = "%s-%s" % (target, arch)
                print("  build %s [%s] -> %s" % (e["source"], p, at))
                if run(["docker", "build", "-t", at, e["source"]]) or run(["docker", "push", at]):
                    sys.stderr.write("✗ build failed for %s [%s]\n" % (name, p))
                    rc = 1
        if not args.push:
            print("\nlog in (each machine):  docker login ghcr.io -u <user>   (token needs write:packages)")
            print("push per arch:           ducktest publish-images --push        (mirrors: any one box; builds: amd + arm)")
            print("then stitch, once:       ducktest publish-images --finalize --push")
    return rc


def _pull_images(args):
    """Pre-pull the images the resources will RUN — warm the cache, fail fast if one is unpullable.

    Pulls each registered resource's SERVED ref: the public ghcr image when ``DUCKTEST_IMAGE_SOURCE=ghcr``
    (the default), else the upstream. CI runs this before the docker tier so a missing/broken image fails
    in an obvious step instead of mid-test; a dev runs the same line to warm a cold cache. Host-arch only
    (plain ``docker pull``), which is exactly the slice the tier boots on this machine.
    """
    from .resources import azurite, minio  # noqa: F401 — import populates the registry
    from .resources._images import IMAGE_SOURCE, registry, served_image

    imgs = registry()
    if not imgs:
        sys.stderr.write("✗ no resource images registered\n")
        return 1
    print("pull served images (source=%s; %s)" % (IMAGE_SOURCE, "dry run" if args.dry_run else "PULL"))
    rc = 0
    for name, e in imgs:
        if e["kind"] == "build" and IMAGE_SOURCE != "ghcr":
            # a build image under source=upstream has no ref to pull — its `source` is a Dockerfile dir.
            print("  skip %s (build kind, source=upstream — built locally, nothing to pull)" % name)
            continue
        ref = served_image(name, e["source"], e["pin"])
        print("  $ docker pull %s" % ref)
        if args.dry_run:
            continue
        if subprocess.run(["docker", "pull", ref]).returncode:
            sys.stderr.write("✗ pull failed for %s (%s)\n" % (name, ref))
            rc = 1
    return rc


def main(argv=None):
    parser = argparse.ArgumentParser(prog="ducktest", description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    p_cfg = sub.add_parser("configure", help="write pytest.ini + a starter pyproject.toml so pytest / uv run pytest work")
    p_cfg.add_argument("dir", nargs="?", default=".", help="target repo dir (default: cwd)")
    p_cfg.set_defaults(func=_configure)

    p_pub = sub.add_parser("publish-images", help="publish the resource images into ghcr (core docker, no buildx)")
    p_pub.add_argument("--push", action="store_true", help="actually run docker (default: print the plan only)")
    p_pub.add_argument(
        "--finalize",
        action="store_true",
        help="stitch the per-arch tags into the multi-arch manifest (run after --push on every arch)",
    )
    p_pub.add_argument(
        "--namespace",
        default=None,
        metavar="NS",
        help="ghcr namespace (default: $DUCKTEST_IMAGE_NS or ghcr.io/benfleis)",
    )
    p_pub.set_defaults(func=_publish_images)

    p_pull = sub.add_parser("pull-images", help="pre-pull the resources' served images (warm cache / fail fast before the docker tier)")
    p_pull.add_argument("--dry-run", action="store_true", help="print the docker pull plan, run nothing")
    p_pull.set_defaults(func=_pull_images)

    # KNOWN LIMITATION (found in code review, 2026-07-14, not fixed): argparse can't disambiguate a
    # dash-leading pytest_args token from the optional `keys` positional when `keys` is omitted --
    # `ducktest teardown-service -p no:cacheprovider` errors "unrecognized arguments" instead of
    # targeting all services + forwarding -p. A `--` separator does NOT help either: argparse still
    # greedily binds the first REMAINDER-adjacent token to `keys` (`teardown-service -- -p no:x` parses
    # `-p` into `keys`, silently mistargeting the service filter instead of erroring). Workaround: pass
    # `keys` explicitly (`teardown-service '*' -p no:cacheprovider`) whenever forwarding a pytest flag.
    for name, flag, helptext in (
        ("provision-service", "--provision-service", "start declared service(s) and leave them running"),
        ("teardown-service", "--teardown-service", "stop declared service(s)"),
    ):
        p = sub.add_parser(name, help=helptext)
        p.add_argument("keys", nargs="?", default=None, help="comma-list of service keys (default: all)")
        p.add_argument(
            "pytest_args",
            nargs=argparse.REMAINDER,
            help="extra args forwarded to pytest (pass `keys` explicitly, e.g. '*', when using this -- "
            "a dash-leading arg can't be forwarded if `keys` is omitted, see the comment above)",
        )
        p.set_defaults(func=lambda a, _flag=flag: _service_cmd(a, _flag))

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
